export const LIST_COUNTRY = 'LIST_COUNTRY';
export const LIST_COUNTRY_SUCCESS = 'LIST_COUNTRY_SUCCESS';
export const LIST_COUNTRY_NAME = 'LIST_COUNTRY_NAME';
export const LIST_COUNTRY_NAME_SUCCESS = 'LIST_COUNTRY_NAME_SUCCESS';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const EDITED_COUNTRY = 'EDITED_COUNTRY';